### ISSUE TITLE
Unexpected Token error

### ISSUE THREAD

**Issue by uncovery** [PrismarineJS/burger-extractor#7]
Hi, I am trying to run this. I successfully created a burger-json file. I am trying to run this on it, but I get this issue:
```

src/index.js:59
const run = async () => {
                  ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

```

any idea what I could be doing wrong?

**Comment by uncovery** [comment]
nevermind, seems my nodejs is outdated.
